name: CI/CD pipeline to Docker Hub and AWS EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/prediccion-emociones:latest .

      - name: Docker push to Dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/prediccion-emociones:latest

      - name: Login into the server
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            if docker ps --all | grep prediccion-emociones; then
              docker stop prediccion-emociones
              docker rm prediccion-emociones
            fi
            docker pull ${{ secrets.DOCKER_USERNAME }}/prediccion-emociones:latest
            docker run -d --name prediccion-emociones -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/prediccion-emociones:latest

